# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_recurso', models.TextField(max_length=20, unique=True)),
                ('descripcion_recurso', models.TextField(blank=True, max_length=50)),
                ('estado_recurso', models.CharField(choices=[('DIS', 'DISPONIBLE'), ('SOL', 'SOLICITADO'), ('RES', 'RESERVADO'), ('MAN', 'EN MANTENIMIENTO'), ('USO', 'EN USO'), ('NDE', 'NO DEVUELTO'), ('FUS', 'FUERA DE USO')], default='DIS', max_length=3)),
            ],
            options={
                'permissions': (('per_crear_recurso', 'Puede crear recurso'), ('per_eliminar_recurso', 'Puede eliminar recurso'), ('per_ver_recurso', 'Puede ver recurso'), ('per_editar_recurso', 'Puede editar recurso')),
            },
        ),
    ]
