# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 05:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_documento', models.TextField(max_length=20)),
                ('direccion', models.TextField(blank=True, max_length=100, null=True)),
                ('telefono', models.TextField(blank=True, max_length=20, null=True)),
                ('prioridad', models.CharField(choices=[('ADM', 'ADMINISTRADOR DE RECURSOS'), ('TIT', 'PROFESOR TITULAR'), ('ADJ', 'PROFESOR ADJUNTO'), ('ASI', 'PROFESOR ASISTENTE'), ('ENC', 'ENCARGADO DE CATEDRA'), ('AUX', 'AUXILIAR DE ENSENHANZA'), ('ALU', 'ALUMNO'), ('FUN', 'FUNCIONARIO'), ('NON', 'NO-CATEGORIZADO')], default='NON', max_length=3)),
                ('rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('per_crear_usuario', 'Puede crear usuario'), ('per_editar_usuario', 'Puede editar usuario'), ('per_eliminar_usuario', 'Puede eliminar usuario'), ('per_ver_usuario', 'Puede ver usuario')),
            },
        ),
    ]
