# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipos_recursos', '0002_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('NUE', 'NUEVO'), ('PEN', 'PENDIENTE'), ('ATE', 'ATENDIDO')], default='NUE', max_length=3)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_recursos.Recurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reclamos',
                'permissions': (('per_crear_reclamo', 'Puede crear reclamo'), ('per_modificar_reclamo', 'Puede modificar estado reclamo'), ('per_ver_reclamo', 'Puede ver ')),
            },
        ),
    ]
