# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamo',
            options={'permissions': (('per_crear_reclamo', 'Puede crear reclamo'), ('per_modificar_reclamo', 'Puede modificar estado reclamo'), ('per_ver_reclamo', 'Puede ver '))},
        ),
        migrations.AddField(
            model_name='reclamo',
            name='estado',
            field=models.CharField(choices=[('N', 'NUEVO'), ('P', 'PENDIENTE'), ('A', 'ATENDIDO')], default='N', max_length=1),
        ),
    ]
