# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipos_recursos', '0002_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True)),
                ('hora_ini', models.TimeField(blank=True)),
                ('hora_fin', models.TimeField(blank=True)),
                ('descripcion', models.CharField(blank=True, max_length=70)),
                ('estado', models.CharField(choices=[('RE', 'REALIZADA'), ('CA', 'CANCELADA'), ('RA', 'REASIGNADA'), ('EC', 'EN CURSO'), ('ND', 'NO DEVUELTO'), ('TE', 'TERMINADA')], default='RE', max_length=2)),
                ('recurso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tipos_recursos.Recurso')),
                ('tipo_recurso', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tipos_recursos.TipoRecurso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservas',
                'permissions': (('per_realizar_reserva', 'Puede reservar'), ('per_cancelar_reserva', 'Puede cancelar la reserva'), ('per_listar_sus_reservas', 'Puede ver sus reservas'), ('per_listar_reservas', 'Puede listar las reservas')),
            },
        ),
    ]
