# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos_recursos', '0002_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(max_length=50)),
                ('tipo_mantenimiento', models.CharField(choices=[('PRE', 'PREVENTIVO'), ('COR', 'CORRECTIVO')], default='PRE', max_length=3)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('mantenimiento_programado', models.DateField()),
                ('costo', models.IntegerField()),
                ('estado', models.CharField(choices=[('INI', 'INICIADO'), ('FIN', 'FINALIZADO')], default='INI', max_length=3)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_recursos.Recurso')),
                ('tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_recursos.TipoRecurso')),
            ],
            options={
                'permissions': (('per_crear_mantenimiento_recurso', 'Puede crear el mantenimiento de un recurso'), ('per_modificar_mantenimiento_recurso', 'Puede modificar el mantenimiento de un recurso'), ('per_lista_mantenimientos', 'Puede listar todos los mantenimientos del tipo de recurso del que esta encargado')),
                'db_table': 'mantenimiento',
            },
        ),
    ]
