# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='mantenimiento_programado',
        ),
    ]
