# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.TextField(max_length=30)),
                ('mensaje', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'registro_usuario',
                'permissions': (('per_configuracion_registro_usuario', 'Puede ver la plantilla para el envio de notificaciones de registro de usuario'),),
            },
        ),
    ]
