# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 23:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('nombre', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
                ('lista_caracteristicas', django.contrib.postgres.fields.jsonb.JSONField()),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
            ],
            options={
                'permissions': (('per_crear_tiporecurso', 'Puede crear tipo recurso'), ('per_eliminar_tiporecurso', 'Puede eliminar tipo recurso'), ('per_ver_tiporecurso', 'Puede ver tipo recurso'), ('per_editar_tiporecurso', 'Puede editar tipo recurso')),
            },
        ),
    ]
