# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('nombre', models.TextField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
                ('lista_caracteristicas', models.TextField()),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
            ],
        ),
    ]
