# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporecurso',
            name='lista_caracteristicas',
            field=models.TextField(),
        ),
    ]
