# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiporecurso',
            options={'permissions': (('per_crear_tiporecurso', 'Puede crear tipo recurso'), ('per_eliminar_tiporecurso', 'Puede eliminar tipo recurso'), ('per_ver_tiporecurso', 'Puede ver tipo recurso'), ('per_editar_tiporecurso', 'Puede editar tipo recurso'))},
        ),
    ]
