# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_recursos', '0002_auto_20170421_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=50)),
            ],
            options={
                'permissions': (('per_crear_estado', 'Puede crear estado de recurso'), ('per_eliminar_estado', 'Puede eliminar estado de recurso'), ('per_ver_estado', 'Puede ver estado de recurso'), ('per_editar_estado', 'Puede editar estado de recurso')),
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('codigo_recurso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_recurso', models.TextField(max_length=50)),
                ('descripcion_recurso', models.TextField(max_length=50)),
                ('activo', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('tipo_recurso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tipos_recursos.TipoRecurso')),
            ],
            options={
                'permissions': (('per_crear_recurso', 'Puede crear recurso'), ('per_eliminar_recurso', 'Puede eliminar recurso'), ('per_ver_recurso', 'Puede ver recurso'), ('per_editar_recurso', 'Puede editar recurso')),
            },
        ),
    ]
