# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_recursos', '0003_auto_20170421_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporecurso',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiporecurso',
            name='nombre',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
