# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_recursos', '0002_auto_20170421_2022'),
        ('tipos_recursos', '0004_auto_20170422_0308'),
    ]

    operations = [
    ]
