# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_recursos', '0004_auto_20170421_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiporecurso',
            name='id',
        ),
        migrations.AlterField(
            model_name='tiporecurso',
            name='nombre',
            field=models.TextField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
